mybatis-plus:
  type-aliases-package: com.academic.user.dto
#  mapper-locations: classpath:/mapper/**.xml
spring:
  application:
    name: user-service
  datasource:
    datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_USER_DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USER}
    password: "${MYSQL_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081

spring.mail:
  host: ${SMTP_HOST}
  port: ${SMTP_PORT}
  username: ${SMTP_USER}
  password: ${SMTP_PASS}
  properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # 启用TLS
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000