services:
  # user-service:
  #   build: ./services/user-service
  #   environment:
  #     - MYSQL_HOST=${MYSQL_HOST}
  #     - MYSQL_PORT=${MYSQL_PORT}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_USER_DB_NAME=${MYSQL_USER_DB_NAME}
  #   expose:
  #     - "8001"

  # achievement-service:
  #   build: ./services/achievement-service
  #   env_file:
  #     - .env
  #   expose:
  #     - "8002"

  file-service:
    build: ./services/file-service
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_FILE_DB_NAME=${MYSQL_FILE_DB_NAME}
    expose:
      - "8005"
    depends_on:
      - mysql

  # data-sync-service:
  #   build: ./services/data-sync-service
  #   env_file:
  #     - .env
  #   expose:
  #     - "8004"

  # analytics-service:
  #   build: ./services/analytics-service
  #   env_file:
  #     - .env
  #   expose:
  #     - "8006"

  # admin-service:
  #   build: ./services/admin-service
  #   environment:
  #     - MYSQL_HOST=${MYSQL_HOST}
  #     - MYSQL_PORT=${MYSQL_PORT}
  #     - MYSQL_USER=${MYSQL_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_ADMIN_DB_NAME=${MYSQL_ADMIN_DB_NAME}
  #     - MONGODB_HOST=${MONGO_HOST}
  #     - MONGODB_PORT=${MONGO_PORT}
  #     - MONGODB_USER=${MONGO_USER}
  #     - MONGODB_PASSWORD=${MONGO_PASSWORD}
  #     - MONGODB_ADMIN_DB_NAME=${MONGO_ADMIN_DB_NAME}
  #   expose:
  #     - "8003"

  gateway-service:
    build: ./services/gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql