spring:
  application:
    name: analytics-service
server:
  port: 8084

achievement:
  service:
    url: http://localhost:8082

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
