spring:
  application:
    name: data-sync-service
server:
  port: 8086

achievement:
  service:
    url: http://localhost:8082

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
