#!/bin/bash
set -e

ACHIEVE_DB_NAME=${ACHIEVE_DB_NAME}
FILE_DB_NAME=${FILE_DB_NAME}
ACHIEVE_DB_NAME=${ACHIEVE_DB_NAME}
MYSQL_USER=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}


for i in {1..30}; do
  if mysqladmin ping -uroot >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

mysql -uroot <<-EOS
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';

CREATE DATABASE IF NOT EXISTS \`$ACHIEVE_DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS \`$FILE_DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS \`$ADMIN_DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

GRANT ALL PRIVILEGES ON \`$ACHIEVE_DB_NAME\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON \`$FILE_DB_NAME\`.* TO '${MYSQL_USER}'@'%';
GRANT ALL PRIVILEGES ON \`$ADMIN_DB_NAME\`.* TO '${MYSQL_USER}'@'%';

FLUSH PRIVILEGES;
EOS
