CREATE TABLE IF NOT EXISTS auth_requests (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  proceeding_admin_id VARCHAR(128),
  applicant_user_id VARCHAR(128) NOT NULL,
  real_name VARCHAR(256) NOT NULL,
  id_number VARCHAR(128) NOT NULL,
  phone VARCHAR(64) NOT NULL,
  organization VARCHAR(256) NOT NULL,
  position VARCHAR(256) NOT NULL,
  application_reason TEXT NOT NULL,
  auth_type VARCHAR(64) NOT NULL,
  attachments TEXT,
  status VARCHAR(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reports (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  proceeding_admin_id VARCHAR(128),
  reporter_id VARCHAR(128) NOT NULL,
  type VARCHAR(32) NOT NULL,
  target_id VARCHAR(128) NOT NULL,
  reason TEXT,
  status VARCHAR(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_message_states (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  user_id VARCHAR(128) NOT NULL,
  message_id VARCHAR(128) NOT NULL,
  state VARCHAR(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_user_message_user_id (user_id)
);
