server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service-java:3001
          predicates:
            - Path=/api/users/**
        - id: achievement-service
          uri: http://achievement-service-java:3002
          predicates:
            - Path=/api/achievements/**
        - id: file-service
          uri: http://file-service-java:3005
          predicates:
            - Path=/internal/files/**
